version: '2.1'

services:
  
  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_Name}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
  app:
    container_name: app
    build: .
    command: bash -c  "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    

    
